const names = require('./4-names')
const sayhi = require('./5-utils')
const data = require('./6-alternative-flavour')
require('./7-mind-greenade')
//  console.log(data)
// sayhi('susan')
// sayhi(names.john)
sayhi(names.peter)